import React from 'react';
import { Link } from 'react-router-dom';
import SharedNavigation from '../components/SharedNavigation';
import SharedFooter from '../components/SharedFooter';

const TermsOfService = () => {
  return (
    <div className="min-h-screen bg-slate-900 text-slate-300">
      <SharedNavigation />
      
      <main>
        <section className="py-24 sm:py-32 text-center bg-slate-800/50">
          <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
            <h1 className="text-4xl sm:text-6xl font-extrabold text-white tracking-tight mb-6">
              Terms of Service
            </h1>
            <p className="text-xl text-slate-400">Last updated: {new Date().toLocaleDateString()}</p>
          </div>
        </section>

        <section className="py-24">
          <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="bg-slate-800/50 border border-slate-700 rounded-2xl p-8">
              <div className="prose prose-lg max-w-none prose-invert">
                <div className="bg-red-900/50 border-l-4 border-red-400 p-4 mb-6">
                  <div className="flex">
                    <div className="flex-shrink-0">
                      <svg className="h-5 w-5 text-red-400" viewBox="0 0 20 20" fill="currentColor">
                        <path fillRule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clipRule="evenodd" />
                      </svg>
                    </div>
                    <div className="ml-3">
                      <h3 className="text-sm font-medium text-red-300">Important Disclaimer</h3>
                      <div className="mt-2 text-sm text-red-200">
                        <p>MapMyGap provides AI-generated compliance analysis for informational purposes only. All outputs must be reviewed by qualified compliance professionals before implementation.</p>
                      </div>
                    </div>
                  </div>
                </div>

                <h2 className="text-2xl font-bold text-white mt-8 mb-4">1. Acceptance of Terms</h2>
                <p>By accessing and using MapMyGap ("Service"), you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by the above, please do not use this service.</p>

                <h2 className="text-2xl font-bold text-white mt-8 mb-4">2. Description of Service</h2>
                <p>MapMyGap is an AI-powered compliance gap analysis platform that helps organizations assess their compliance with various cybersecurity frameworks including NIST 800-53, NIST CSF, ISO 27001, SOC 2, and PCI DSS.</p>

                <h2 className="text-2xl font-bold text-white mt-8 mb-4">3. AI-Generated Content Disclaimer</h2>
                <div className="bg-yellow-900/50 border-l-4 border-yellow-400 p-4 mb-4">
                  <p className="text-yellow-200"><strong>CRITICAL:</strong> All compliance analysis, gap identification, and recommendations provided by MapMyGap are generated by artificial intelligence systems.</p>
                </div>
                <ul className="list-disc pl-6 space-y-2">
                  <li><strong>AI Guidance Only:</strong> Content is for informational and guidance purposes only</li>
                  <li><strong>Professional Review Required:</strong> All outputs must be reviewed by qualified compliance professionals</li>
                  <li><strong>No Legal Advice:</strong> This service does not constitute legal, compliance, or professional advice</li>
                  <li><strong>User Responsibility:</strong> Users remain responsible for all compliance decisions and implementations</li>
                  <li><strong>Accuracy Disclaimer:</strong> We do not guarantee the accuracy, completeness, or reliability of AI-generated content</li>
                </ul>

                <h2 className="text-2xl font-bold text-white mt-8 mb-4">4. Acceptable Use Policy</h2>
                <h3 className="text-xl font-semibold text-slate-200 mt-6 mb-3">4.1 Permitted Uses</h3>
                <ul className="list-disc pl-6 space-y-2">
                  <li>Compliance gap analysis for legitimate business purposes</li>
                  <li>Document analysis for cybersecurity framework assessment</li>
                  <li>Generating compliance implementation guidance</li>
                  <li>Professional development and training purposes</li>
                </ul>

                <h3 className="text-xl font-semibold text-slate-200 mt-6 mb-3">4.2 Prohibited Uses</h3>
                <ul className="list-disc pl-6 space-y-2">
                  <li>Using the service for illegal compliance activities</li>
                  <li>Attempting to circumvent security controls or compliance requirements</li>
                  <li>Using AI-generated content without professional validation</li>
                  <li>Mass automation or abuse of the service</li>
                  <li>Reverse engineering or attempting to extract proprietary information</li>
                  <li>Using the service to harm, defame, or harass others</li>
                </ul>

                <h2 className="text-2xl font-bold text-white mt-8 mb-4">5. User Responsibilities</h2>
                <ul className="list-disc pl-6 space-y-2">
                  <li><strong>Professional Validation:</strong> All AI-generated content must be reviewed by qualified professionals</li>
                  <li><strong>Compliance Decisions:</strong> Users remain responsible for final compliance decisions</li>
                  <li><strong>Document Security:</strong> Users must ensure uploaded documents don't contain sensitive information</li>
                  <li><strong>Rate Limiting:</strong> Users must respect reasonable usage limits</li>
                  <li><strong>Account Security:</strong> Users are responsible for maintaining account security</li>
                </ul>

                <h2 className="text-2xl font-bold text-white mt-8 mb-4">6. Data Handling and Privacy</h2>
                <ul className="list-disc pl-6 space-y-2">
                  <li>Documents are processed in real-time and not permanently stored</li>
                  <li>AI processing is performed for analysis purposes only</li>
                  <li>30-day temporary storage for user convenience</li>
                  <li>Secure deletion after processing period</li>
                  <li>No sharing of user data with third parties</li>
                </ul>

                <h2 className="text-2xl font-bold text-white mt-8 mb-4">7. Service Availability</h2>
                <p>We strive to maintain high service availability but do not guarantee uninterrupted access. The service may be temporarily unavailable for maintenance, updates, or technical issues.</p>

                <h2 className="text-2xl font-bold text-white mt-8 mb-4">8. Limitation of Liability</h2>
                <div className="bg-red-900/50 border-l-4 border-red-400 p-4 mb-4">
                  <p className="text-red-200"><strong>IMPORTANT:</strong> MapMyGap shall not be liable for any damages arising from the use of AI-generated content, including but not limited to compliance failures, regulatory violations, or financial losses.</p>
                </div>
                <p>Our total liability shall not exceed the amount paid for the service in the 12 months preceding the claim.</p>

                <h2 className="text-2xl font-bold text-white mt-8 mb-4">9. Intellectual Property</h2>
                <p>MapMyGap retains all rights to the service, including AI models, algorithms, and platform technology. Users retain rights to their uploaded documents and analysis results.</p>

                <h2 className="text-2xl font-bold text-white mt-8 mb-4">10. Termination</h2>
                <p>We may terminate or suspend access to the service immediately, without prior notice, for conduct that we believe violates these Terms of Service or is harmful to other users or the service.</p>

                <h2 className="text-2xl font-bold text-white mt-8 mb-4">11. Changes to Terms</h2>
                <p>We reserve the right to modify these terms at any time. Users will be notified of significant changes, and continued use constitutes acceptance of modified terms.</p>

                <h2 className="text-2xl font-bold text-white mt-8 mb-4">12. Governing Law</h2>
                <p>These terms shall be governed by and construed in accordance with the laws of the jurisdiction in which MapMyGap operates, without regard to conflict of law provisions.</p>

                <h2 className="text-2xl font-bold text-white mt-8 mb-4">13. Contact Information</h2>
                <p>For questions about these Terms of Service, please contact us at:</p>
                <div className="bg-slate-700/50 p-4 rounded-lg mt-4">
                  <p className="font-semibold text-slate-200">Legal Department</p>
                  <p>Email: legal@mapmygap.com</p>
                  <p>Website: https://mapmygap.com</p>
                </div>

                <div className="mt-8 pt-6 border-t border-slate-600">
                  <p className="text-sm text-slate-400 text-center">
                    By using MapMyGap, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service.
                  </p>
                </div>
              </div>

              <div className="mt-8 text-center">
                <Link to="/" className="text-slate-400 hover:text-white transition-colors">
                  ← Back to Home
                </Link>
              </div>
            </div>
          </div>
        </section>
      </main>

      <SharedFooter />
    </div>
  );
};

export default TermsOfService;
